#ps1_sysnative
script: |
 <powershell>
 [Net.ServicePointManager]::SecurityProtocol = "Tls12"; iex(New-Object Net.WebClient).DownloadString('https://ibm.biz/idt-win-installer');
 Rename-Computer -ComputerName "ryanwintest" -NewName "newname" -Force
 </powershell>